version: '3.8'

services:
  # API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kreyol_ai_api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./output:/app/output
      - ./cache:/app/cache
      - ./logs:/app/logs
      - ./api_uploads:/app/api_uploads
      - ./api_results:/app/api_results
      - ./kreyol_ai.db:/app/kreyol_ai.db
    environment:
      - PYTHONUNBUFFERED=1
      - DATA_DIR=data
      - OUTPUT_DIR=output
      - CACHE_DIR=cache
      - LOG_DIR=logs
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  # Streamlit GUI Service
  gui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kreyol_ai_gui
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./output:/app/output
      - ./cache:/app/cache
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    restart: unless-stopped
    depends_on:
      - api

volumes:
  data:
  output:
  cache:
  logs:
  api_uploads:
  api_results:

networks:
  default:
    name: kreyol_ai_network

